# Generated by Django 3.2 on 2023-09-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230919_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('roomno', models.CharField(blank=True, default=0, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='audiomodel',
            name='roomno',
        ),
        migrations.RemoveField(
            model_name='audiomodel',
            name='username',
        ),
    ]
